// Generated by `npm run travel:import` from photo metadata (EXIF date + GPS reverse-geocoded).
// Edit scripts/travel-manifest.json, not travel.json.
import data from "./travel.json";

export type TravelPhoto = {
  slug: string;
  src: string;
  place: string;
  country: string;
  when: string;
  sort: string;
  source: "gps" | "date" | "seen";
  cc: string; // ISO 3166-1 alpha-2, for the flag cursor
  lat: number | null;
  lon: number | null;
  width: number;
  height: number;
};

export const photos = data as TravelPhoto[];
export const countries = Array.from(new Set(photos.map((p) => p.country))).sort();
